# Generated by Django 4.1.5 on 2023-03-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=2)),
                ('ID', models.IntegerField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('R_date', models.DateTimeField()),
            ],
        ),
    ]
