# Generated by Django 4.1.5 on 2023-03-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='ID',
            new_name='p_id',
        ),
    ]
