# Generated by Django 4.1.5 on 2023-03-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_patient_age_alter_patient_p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='p_id',
        ),
    ]
