# Generated by Django 4.1.5 on 2023-03-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_patient_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='p_id',
            field=models.IntegerField(null=True),
        ),
    ]
