# Generated by Django 4.1.5 on 2023-03-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_patient_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
