# Generated by Django 4.1.5 on 2023-03-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_patient_p_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='R_date',
            new_name='Registeration_date',
        ),
        migrations.AddField(
            model_name='patient',
            name='appointment',
            field=models.DateTimeField(null=True),
        ),
    ]
