# Generated by Django 4.1.5 on 2023-03-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_r_date_patient_registeration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='p_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.BigIntegerField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_number',
            field=models.BigIntegerField(max_length=11, null=True),
        ),
    ]
