# Generated by Django 4.1.5 on 2023-03-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_patient_p_id_patient_patient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Doctor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
