# Generated by Django 4.1.5 on 2023-03-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_patient_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient_profile',
        ),
    ]
